nis_projects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from nis_projects.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('studentapp.urls'), name='studentapp'),
    path('visit/', include('teacherapp.urls'), name='teacherapp'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

studentapp/urls.py
from django.urls import path
from . import views

appname = 'studentapp'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('students/', views.students, name='student_list'),
    path('students/<int:id>/', views.student, name='student'),
    path('students/new', views.add_student, name='add_student'),
    path('ajax/load-students/', views.load_students, name='ajax_load_student'), # AJAX
    path('infocarta/', views.info, name='infocarta'),
    path('appeal/', views.appeal_upload, name='appeal'),
    path('participant/', views.participant_upload, name='participant'),
    
]

studentapp/models.py
import email
from msilib.schema import RadioButton
from django.db import models
from django.forms import RadioSelect, widgets
from json import JSONEncoder


# model of subects

# model of teacher
class Tutor(models.Model):
    first_name = models.CharField(max_length=200, help_text='Имя', blank=True)
    last_name = models.CharField(
        max_length=200, help_text='Имя', blank=True)
    phone_num = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    date_of_birth = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


# model of Kurators
class Kurator(models.Model):
    first_name = models.CharField(max_length=200, help_text='Имя', blank=True)
    last_name = models.CharField(
        max_length=200, help_text='Фамилия', blank=True)
    birth_date = models.DateTimeField(auto_now_add=True)
    tel_numb = models.CharField(
        max_length=150, help_text='Номер телефона', blank=True)
    adress = models.CharField(max_length=200, help_text='Адресс')
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

# model of tarbiyewi


class Vospitatel(models.Model):
    vospitatel_full_name = models.CharField(max_length=200)
    birth_date = models.DateTimeField(auto_now_add=True)
    tel_numb = models.CharField(max_length=100)
    adress = models.CharField(max_length=200, help_text='Адресс')
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.vospitatel_full_name


# model of student
class Category_class(models.Model):
    name = models.CharField(max_length=128, verbose_name="Выберите класс")

    def __str__(self):
        return self.name


class Student(models.Model):
    STATUS_SEX = (
        ('female', 'Женский'),
        ('male', 'Мужской'),
    )

    STATUS_FAMILY = (
        ('полный', 'Полный'),
        ('неполный', 'Неполный'),
    )
    QUANTITY_CHILDS = (
        ('да', 'ДА'),
        ('нет', 'НЕТ'),
    )
    DISABILITY_CHOICES = (
        ('да', 'Да'),
        ('нет', 'Нет'),

    )
    CHOICES_LANG = (
        ('казахский', 'казахский'),
        ('русский', 'русский'),
    )

    category_class = models.ForeignKey(
        Category_class, on_delete=models.CASCADE, verbose_name="Выберите класс")
    full_name = models.CharField(max_length=250, verbose_name='ФИО')
   
    learning_lang = models.CharField(
        max_length=10, choices=CHOICES_LANG, default='каазахский', verbose_name='Язык обучение')
    
    IIN = models.CharField(max_length=15, verbose_name='ИИН')
    disability = models.CharField(
        max_length=20, choices=DISABILITY_CHOICES, default='нет', verbose_name='Инвалидность')
    category_fam = models.CharField(
        max_length=10, choices=STATUS_FAMILY, default='Полный', verbose_name='Тип семьи')
    father_full_name = models.CharField(max_length=200, blank=True, verbose_name='ФИО отца')
    father_educ = models.CharField(max_length=200, blank=True, verbose_name='Образования')
    father_pos = models.CharField(max_length=200, blank=True, verbose_name='Позиция на работе')
    father_org = models.CharField(max_length=250, blank=True, verbose_name='Место работы')
    father_tel = models.CharField(max_length=100, null=True, blank=True, verbose_name='Контактные данные отца')
    mother_full_name = models.CharField(max_length=200, blank=True, verbose_name='ФИО матери')
    mother_educ = models.CharField(max_length=200, blank=True, verbose_name='Образование')
    mother_pos = models.CharField(max_length=200, blank=True, verbose_name='Позиция на работе')
    mother_org = models.CharField(max_length=250, blank=True, verbose_name='Место работы')
    mother_tel = models.CharField(max_length=100, null=True, blank=True, verbose_name='Контактные данные матери')
    large_family = models.CharField(
        max_length=10, choices=QUANTITY_CHILDS, default='нет', verbose_name='Большая семья')
    childs_in_family = models.CharField(
        max_length=10, verbose_name='Количество детей', blank=True)
    adress = models.CharField(max_length=200, verbose_name='Адресс')
    kurator = models.ForeignKey(Kurator, on_delete=models.CASCADE, null=True, verbose_name='Выберите куратора')
    vospitatel = models.ForeignKey(
        Vospitatel, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Выберите воспитателя')

    stud_tutor = models.ForeignKey(
        Tutor, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Выберите тьютора')
    stud_photo = models.ImageField(upload_to='media/', blank=True, verbose_name='Фото')
    stud_nationality = models.CharField(max_length=100, verbose_name='Национальность')
    stud_date_of_birth = models.DateField(verbose_name='Дата рождения')
    stud_age = models.CharField(max_length=200, verbose_name='Возраст ученика')
    stud_gender = models.CharField(
        max_length=10, choices=STATUS_SEX, default='none', verbose_name='Пол')

    stud_email = models.EmailField(null=True, blank=True, verbose_name='Почта')
    stud_tel = models.CharField(max_length=20, null=True, blank=True, verbose_name='Номер телефона')
    

    def __str__(self):
        return self.full_name

    


class AppealCurators(models.Model):
    CHOOSE_TYPE_APPEAL = (
        ('вопросы внешнего суммативного оценивания',
         'вопросы внешнего суммативного оценивания'),
        ('вопросы выбора профессии', 'вопросы выбора профессии'),
        ('вопросы интелектуального развития учащихся (олимпиады, проекты)',
         'вопросы интелектуального развития учащихся (олимпиады, проекты)'),
        ('вопросы к психологической службе', 'вопросы к психологической службе'),
        ('вопросы общей успеваемости', 'вопросы общей успеваемости'),
        ('вопросы опеспечения безопастности', 'вопросы опеспечения безопастности'),
        ('вопросы по изучения второго иностранного языка',
         'вопросы по изучения второго иностранного языка'),
        ('вопросы по содержанию программы и оценивания',
         'вопросы по содержанию программы и оценивания'),
        ('вопросы поведения', 'вопросы поведения'),
        ('личные вопросы', 'личные вопросы'),
        ('не соблюдение внутренних правил школы',
         'не соблюдение внутренних правил школы'),
        ('опаздания на урок', 'опаздания на урок'),
        ('по вызову мед. Работников', 'по вызову мед. Работников'),
        ('по тестированию IELTS', 'по тестированию IELTS'),
        ('по тестированию SAT ', 'по тестированию SAT '),
        ('Разное', 'Разное'),
        ('рекомендации по улучшению работы школы',
         'рекомендации по улучшению работы школы'),

    )
    parent = models.CharField(max_length=200, verbose_name="Родители")
    category_class = models.ForeignKey(Category_class, on_delete=models.CASCADE)
    student = models.ForeignKey( Student, on_delete=models.CASCADE,
     verbose_name="Ученик")
    visited = models.BooleanField(default=False, verbose_name="Посетил")
    by_telephone = models.BooleanField(
        default=False, verbose_name="По телефону")
    by_writing = models.BooleanField(default=False, verbose_name="Письменно")
    date_of_appeal = models.DateField(verbose_name="Время создания")
    type_appeal = models.CharField(
        max_length=200, choices=CHOOSE_TYPE_APPEAL, default='Разное', verbose_name="Выберите тип обращение")
    question = models.TextField(verbose_name="Вопрос")

    



class Participant(models.Model):
    CHOOSE_TYPE = (
        ('ОЛИМПИАДА', 'ОЛИМПИАДА'),
        ('НАУЧНЫЙ ПРОЕКТ', 'НАУЧНЫЙ ПРОЕКТ'),
        ('КРУЖОК', 'КРУЖОК'),
    )
    category_class = models.ForeignKey(
        Category_class, on_delete=models.CASCADE, verbose_name="Выберите класс")
    student = models.ForeignKey(
        Student, on_delete=models.CASCADE, verbose_name="Ученик")
    title = models.CharField(max_length=250, verbose_name="Название")
    category = models.CharField(
        max_length=250, choices=CHOOSE_TYPE, verbose_name='Выберите тип деятельности')
    date_of_participant = models.DateField(verbose_name='Дата участие')
    result = models.FileField(
        upload_to="pdf/%Y/%m/%d/", verbose_name='Результат')

studentapp/forms.py
from tkinter import Widget
from .models import AppealCurators, Student, Participant, Category_class
import json
from django import forms
from crispy_forms.layout import Layout, Field
from django.contrib.admin.widgets import AdminDateWidget


class DateInput(forms.DateInput):
    input_type = 'date'


# class ApealForm(forms.Form):

#     CHOOSE_TYPE_APPEAL = (
#         ('вопросы внешнего суммативного оценивания',
#          'вопросы внешнего суммативного оценивания'),
#         ('вопросы выбора профессии', 'вопросы выбора профессии'),
#         ('вопросы интелектуального развития учащихся (олимпиады, проекты)',
#          'вопросы интелектуального развития учащихся (олимпиады, проекты)'),
#         ('вопросы к психологической службе', 'вопросы к психологической службе'),
#         ('вопросы общей успеваемости', 'вопросы общей успеваемости'),
#         ('вопросы опеспечения безопастности', 'вопросы опеспечения безопастности'),
#         ('вопросы по изучения второго иностранного языка',
#          'вопросы по изучения второго иностранного языка'),
#         ('вопросы по содержанию программы и оценивания',
#          'вопросы по содержанию программы и оценивания'),
#         ('вопросы поведения', 'вопросы поведения'),
#         ('личные вопросы', 'личные вопросы'),
#         ('не соблюдение внутренних правил школы',
#          'не соблюдение внутренних правил школы'),
#         ('опаздания на урок', 'опаздания на урок'),
#         ('по вызову мед. Работников', 'по вызову мед. Работников'),
#         ('по тестированию IELTS', 'по тестированию IELTS'),
#         ('по тестированию SAT ', 'по тестированию SAT '),
#         ('Разное', 'Разное'),
#         ('рекомендации по улучшению работы школы',
#          'рекомендации по улучшению работы школы'),

#     )
#     parent = forms.CharField(max_length=200)
#     klass = forms.ModelChoiceField(Category_class.objects.all())
#     student = forms.ModelChoiceField(Student.objects.all())
#     visited = forms.BooleanField()
#     by_telephone = forms.BooleanField()
#     by_writing = forms.BooleanField()
#     date_of_appeal = forms.DateField()
#     type_appeal = forms.ChoiceField(
#         max_length=200, choices=CHOOSE_TYPE_APPEAL, default='Разное')
#     question = forms.TextField()


class AppealForms(forms.ModelForm):
    class Meta:
        model = AppealCurators
        fields = '__all__'
        widgets = {
            'date_of_appeal': DateInput(),
            'question': forms.Textarea(attrs={'rows': 4}),
        }
        labels = {
            "parent": "Родители",
            "category_class": "Выберите класс",
            "student": "Выберите ученика",
            "visited": "Посетил",
            "date_of_appeal": "Дата обращение",
            "type_appeal": "Выберите тип обращение",
            "question": "Вопрос обращение"
            }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['student'].queryset = Student.objects.none()

        if 'category_class' in self.data:
            try:
                category_class_id = int(self.data.get('category_class'))
                self.fields['student'].queryset = Student.objects.filter(category_class_id=category_class_id).order_by('name')
            except (ValueError, TypeError):
                pass # invalid input from the client;ignore and fallback to empty student queryset
        elif self.instance.pk:
            self.fields['student'].queryset = self.instance.category_class.student_set.order_by('name')


class ParticipantForm(forms.ModelForm):

    class Meta:
        model = Participant
        fields = '__all__'
        widgets = {
            'date_of_participant': DateInput(),
        }

    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['student'].queryset = Student.objects.none()

        if 'category_class' in self.data:
            try:
                category_class_id = int(self.data.get('category_class'))
                self.fields['student'].queryset = Student.objects.filter(category_class_id=category_class_id).order_by('name')
            except (ValueError, TypeError):
                pass # invalid input from the client;ignore and fallback to empty student queryset
        elif self.instance.pk:
            self.fields['student'].queryset = self.instance.category_class.student_set.order_by('name')


class AddStudent(forms.ModelForm):
    class Meta:
        model = Student

        fields = '__all__'
        widgets = {
            'stud_date_of_birth':DateInput(),

        }

studentapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib import messages
from django.http import JsonResponse
from studentapp.forms import AppealForms, ParticipantForm, AddStudent
from .models import Student, AppealCurators
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import StudentFilter


def index(request):
    return render(request, 'studentapp/index.html')


def students(request):
    object_list = Student.objects.all()
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        students = paginator.page(page)
    except PageNotAnInteger:
        students = paginator.page(1)
    except EmptyPage:
        students = paginator.page(page.num_pages)

    myfilter = StudentFilter(request.GET, queryset=object_list)   
    return render(request, 'studentapp/students_page.html', {'students': students, 'page': page, 'myfilter': myfilter})


def student(request, id):
    student = Student.objects.get(id=id)
    return render(request, 'studentapp/single_page.html', {'student': student})


# def by_klass(request):
#     indv_klass = Student.objects.filter(klass=Student.klass)
#     return render(request, 'studentapp/by_class.html', {'indv_klass': indv_klass})


def info(request):
    chartqueryset = Student.objects.all().count()
    print(chartqueryset)
    return render(request, 'studentapp/info.html', {'chartqueryset': chartqueryset})


def appeal_upload(request):
    if request.method == 'POST':
        form = AppealForms(request.POST)
        if form.is_valid():
            form.save()
            return redirect('appeal')
        else:
            return HttpResponse('Form is not valid')
    else:
        form = AppealForms()
    return render(request, 'studentapp/appeal.html', {'form': form})


# AJAX
def load_students(request):
    category_class_id = request.GET.get('category_class')
    students_list = Student.objects.filter(category_class_id=category_class_id)
    return render(request, 'studentapp/student_dropdown_list_options.html', {'students_list': students_list})
    print(list(students.values('id', 'full_name')))
    return JsonResponse(list(students.values('id', 'full_name')), safe=False)

def participant_upload(request):
    if request.method == 'POST':
        form = ParticipantForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=True)
            return redirect('index')
        else:
            return HttpResponse('Form is not valid')
    else:
        form = ParticipantForm()
    return render(request, 'studentapp/participant.html', {'form': form})


def add_student(request):
    if request.method == 'POST':
        student_form = AddStudent(request.POST, request.FILES)
        if student_form.is_valid():
            student_form.save()
            return redirect('student_list')
        else:
            return HttpResponse('Form is not valid')
    else:
        student_form = AddStudent()
    return render(request, 'studentapp/add_student.html', {'student_form': student_form})
    

studentapp/templates/studentapp/add_student.html
{% extends 'studentapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}

{% endblock %}


{% block content %}
  <!-- Optional JavaScript; choose one of the two! -->
  
<div class="container p-4" style="background-color: #fff;">

    <form method="post" class="form-group" enctype="multipart/form-data">
        <h2>Добавить ученика</h2>
        {% csrf_token %}
        <div class="form-row">
            
            <div class="form-group col-md-6">
                {{student_form.full_name|as_crispy_field:"bootstrap"}}
            </div>
          <div class="form-group col-md-6">
                {{student_form.IIN|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.stud_nationality|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.stud_date_of_birth|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.stud_age|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.stud_gender|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.stud_email|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.stud_tel|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
            {{student_form.category_class|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.learning_lang|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.category_fam|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.disability|as_crispy_field}}
            </div>
        </div>
            {{student_form.stud_photo|as_crispy_field}}

                {{student_form.father_full_name|as_crispy_field}}
        <div class="form-row form-border">
            <div class="form-group col-md-6">
                {{student_form.father_educ|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.father_pos|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.father_org|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.father_tel|as_crispy_field}}
            </div>
        </div>
                {{student_form.mother_full_name|as_crispy_field}}
        <div class="form-row form-border">
            <div class="form-group col-md-6">
                {{student_form.mother_educ|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.mother_pos|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.mother_org|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.mother_tel|as_crispy_field}}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {{student_form.large_family|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.childs_in_family|as_crispy_field}}
            </div>
        </div>
            {{student_form.adress|as_crispy_field}}
        <div class="form-row">
            <div class="form-group col-md-6">
                {{student_form.kurator|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.stud_tutor|as_crispy_field}}
            </div>
            <div class="form-group col-md-6">
                {{student_form.vospitatel|as_crispy_field}}
            </div>
        </div> 
        
        <button type="submit" class="btn btn-success">Сохранить</button>


    </form>
</div> 
{% endblock %}

studentapp/templates/studentapp/appeal.html
{% extends 'studentapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}

{% endblock %}


{% block content %}
  <!-- Optional JavaScript; choose one of the two! -->
  
<div class="container p-4" style="background-color: #fff;">

    <form method="post" class="form-group" id="appealForm" data-student-url="{% url 'ajax_load_student' %}">
        <h2>Обращение к кураторам</h2>
        {% csrf_token %}

        {{form|crispy}}
        <button type="submit" class="btn btn-success">Сохранить</button>


    </form>
</div> 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>


<script>

    $("#id_category_class").change(function () {
        var url = $("#appealForm").attr("data-student-url");  // get the url of the `load_cities` view
        var category_classId = $(this).val();  // get the selected country ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                    'category_class': category_classId        // add the country id to the GET parameters

            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_student").html(data);  // replace the contents of the city input with the data that came from the server
                

                // let html_data = '<option value="">---------</option>';
                // data.forEach(function (student) {
                //     html_data += `<option value="${student.id}">${student.name}</option>`
                // });
                // console.log(html_data);
                // $("#id_student").html(html_data);

        
                }
            });

    });
</script>


{% endblock %}

studentapp/templates/studentapp/base.html
{% load static %}



<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  
  <link rel="stylesheet" href="{% static 'css/style.css ' %}">

  <title>{% block title %} {% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-light bg-light mb-3">
    <div class="container">
      <a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}" height="60" alt="logo" ></a>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbarNav" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto" id="navbarNav">
          <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Главная</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'student_list' %}">Контингент</a></li>
          <li class="nav-item"><a class="nav-link" href="">Сайт школы</a></li>
          <li class="nav-item"><a class="nav-link" href="">Расписание</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'add_student' %}">Добавить ученика</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'appeal' %}">Кураторам</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'participant' %}">Участие</a></li>
          <li class="nav-item"><a class="nav-link" href="">Вход</a></li>
        </ul>
      </div>
    </div>
  </nav>

  {% block slider %}


  {% endblock %}
  <div class="container">
    {% block content %}


    {% endblock %}
  </div>


  <!-- Optional JavaScript; choose one of the two! -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>
  <script>
    $('.port-item').click(function () {
      $('.collapse').collapse('hide');
    });
  </script>

 
</body>

</html>

studentapp/templates/studentapp/by_class.html
{% extends 'studentapp/base.html' %}

{% load static %}
{% block extrahead %}

{% endblock%}

{% block title %}{% endblock %}

{% block content %}



<div class="container">
    <div class="row">
        {% for single_klass in indv_klass %}
        <div class="col-sm-6 col-md-4 col-lg-3 mb-3">

            <div class="card">
                <img src="{% static 'img/person-jpg.png'%}" class="card-img-top img-thumbnail" alt="" width="80"
                    height="">
                <div class="card-body">
                    <h4 class="card-title text-center"><a href="{% url 'student' student.pk %}">{{student.first_name}}
                            {{student.last_name}}</a></h4>
                    <h6 class="card-subtitle text-center"><a href="">7A</a></h6>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>

    {% endblock %}

studentapp/templates/studentapp/index.html
{% extends 'studentapp/base.html' %}
{% load static %}
{% block title %} {% endblock %}

{% block slider %}
	<div class="container-fluid p-0">
		<img src="{% static 'img/students1.jpg'  %}" alt="" style=" width:100vw; height: 100vh;">
	</div>

{% endblock %}
{% block content %}
	
		
{% endblock %}

studentapp/templates/studentapp/participant.html
{% extends 'studentapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}

{% endblock %}


{% block content %}
<div class="container p-4" style="background-color: #fff;">

    <form method="post" class="form-group" id="participantForm" data-student-url="{% url 'ajax_load_student' %}">
        <h2>Участие</h2>
        {% csrf_token %}

        {{form|crispy}}
        <button type="submit" class="btn btn-success">Сохранить</button>


    </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script>

    $("#id_category_class").change(function () {
        var url = $("#participantForm").attr("data-student-url");  // get the url of the `load_cities` view
        var category_classId = $(this).val();  // get the selected country ID from the HTML input
        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                    'category_class': category_classId        // add the country id to the GET parameters

            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_student").html(data);  // replace the contents of the city input with the data that came from the server
                

                // let html_data = '<option value="">---------</option>';
                // data.forEach(function (student) {
                //     html_data += `<option value="${student.id}">${student.name}</option>`
                // });
                // console.log(html_data);
                // $("#id_student").html(html_data);

        
                }
            });

    });
</script>
{% endblock %}

studentapp/templates/studentapp/student_dropdown_list_options.html
<option value="">---------</option>
{% for student in students_list %}
<option value="{{ student.pk }}">{{ student.full_name }}</option>
{% endfor %}